[project]
name = "mojing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "labelme>=5.11.2",
    "pyqt5-qt5==5.15.2",
    "ultralytics>=8.4.12",
    "websockets>=16.0",
]
